### ISSUE TITLE
Redefining `require` for all `*-spec.js` files

### ISSUE THREAD

**Issue by dtothefp** [halt-hammerzeit/require-hacker#2]
I'm working on how to figure out to have an end to end test that can specify the browsers/devices it should load in by exporting them. I'd like to some how hijack the `require` calls for `*-spec` and then just be able to parse what is `export`ed from the test file without it not executing the rest of the JavaScript test code in the file. I'm wondering if this is possible with this module and if so you could point me in the right direction:

example:

```js
import {expect} from 'chai';
import setup from '../../config/e2e-setup';

export default {
  desktop: ['chrome'],
  mobile: ['iphone']
}

const url = '/';

describe('local homepage parallel', function() {
  let client;

  before(function() {
    client = setup();
    return client.url(url);
  });

  it('should get the page title', (cb) => {
    client.getTitle().then((title) => {
      expect(title).to.eq('FrontendBoilerplate');
      cb();
    });
  });
});
```

and I just want to parse what is `export`ed

**Comment by halt-hammerzeit** [comment]
I didn't get the idea what you are aiming for but I guess you could try to parse the AST
http://jointjs.com/demos/javascript-ast
And if it has some kind of a special node for "export"ed object then you could extract it (if it doesn't require javascript execution, i.e. consists of constant values).
They use Acorn.js in eslint
https://github.com/ternjs/acorn

I haven't done such a thing and it seems a time consuming functionality to implement.
Maybe there are other ways for you to achieve your goals.

**Comment by halt-hammerzeit** [comment]
Or you could set up a global hook inside of which there would be a regular expression match test for filename.
And then extract another regexp, something like `/export default \{(.*)\}` and then `JSON.parse` it.

**Comment by dtothefp** [comment]
Thanks for the suggestion, I ended up doing something like this because didn't think I could do a regex that would match considering line breaks and potential nested brackets. This seems to work

```js
  requireHacker.global_hook('specs', path => {
    if (/-spec\.js/.test(path)) {
      const content = fs.readFileSync(path, {encoding: 'utf8'});
      const re = /export default *\{/;
      const match = re.exec(content);
      const start = match.index;
      let str = match[0];
      const rest = content.split(str).splice(-1)[0];
      let open = 1;

      for(let i = 0; i < rest.length; i += 1) {
        const chr = rest[i];

        if (!open) {
          break;
        } else if (chr === '}') {
          open -= 1;
        } else if (chr === '{') {
          open += 1;
        }

        str += chr;
      }

      const es5Export = str.replace(re, 'module.exports = {');

      return es5Export;
    }
  });
```
