### ISSUE TITLE
Error: Invalid file extension "style.js"

### ISSUE THREAD

**Issue by amirmohsen** [halt-hammerzeit/require-hacker#4]
I am using your other package (webpack-isomorphic-tools) which relies on this package and I keep getting this error:

Invalid file extension "style.js"
at Object.extension ([PROJECT_ROOT]\node_modules\require-hacker\babel-transpiled-modules\require hacker.js:337:10)

I have this in my webpack-isomorphic-tools.js:

```
style_modules: {
    extension: 'style.js',
    // etc...
}
```

I use [postcss-js](https://github.com/postcss/postcss-js) in my setup hence the "style.js" extension.

**Comment by halt-hammerzeit** [comment]
Yes, it only supports valid filename extensions
https://en.wikipedia.org/wiki/Filename_extension
https://github.com/nodejs/node/blob/master/lib/module.js#L445-L447

Theoretically this non-standard functionality could be implemented with "global hooks" but I don't see any motivation in doing that.

**Comment by amirmohsen** [comment]
Well, there's no widely agreed CSS-in-JS extension in the community (I got mine from here: https://github.com/postcss/postcss-loader#js-styles) and multiple extensions are pretty common anyway, particularly in the unix world like "tar.gz" so I am not sure about the whole "valid extension" thing.

Anyway, thanks for the package. It has been useful (except in this one case).

**Comment by halt-hammerzeit** [comment]
@amirmohsen well, that's not for me to decide
https://nodejs.org/api/path.html#path_path_extname_p
