### ISSUE TITLE
Issue with babel?

### ISSUE THREAD

**Issue by loudwinston** [halt-hammerzeit/require-hacker#6]
I'm trying to use `require-hacker` to catch problems with case-insensitive file systems.  For example, if a developer using a case insensitive filesystem requires `foo.js`, when file is actually `Foo.js`, it'll work fine on their machine (Windows or Mac) but will fail when it gets to our development environment which runs on a case sensitive Linux filesystem.

What I'm trying to do is throw an error when you request a file that would be matched on a case-insensitive filesystem, but not on a case-sensitive one.  
Full source code is
```
import requireHacker from 'require-hacker';
import fs from 'fs';
import path from 'path';

requireHacker.global_hook('caseSensitive', (requestedPath, module) => {
  const actualPath = requireHacker.resolve(requestedPath, module);
  const exists = fs.readdirSync(path.dirname(actualPath)).some((file) => {
    return path.basename(requestedPath) === file;
  });

  if (!exists) {
    const errorString = `throw new Error('Cannot find module \'${requestedPath}\' (case-sensitive)');`;
    return errorString;
  }
});

//exists
require('./someCaseSensitivePath.js');

//doesn't exist
require('./somecasesensitivepath.js');
```

When I run this, I get the following error 
```
Error: Cannot find module 'babel-plugin-transform-runtime.caseSensitive'
    at Module._resolveFilename (module.js:325:15)
    at Object.resolve (/Users/loudwinston/app/screening-client/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:321:11)
    at caseSensitiveRequire.js:6:36
    at resolver (/Users/loudwinston/app/screening-client/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:131:17)
    at Function._module3.default._findPath (/Users/loudwinston/app/screening-client/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:436:24)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function._module3.default._resolveFilename (/Users/loudwinston/app/screening-client/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

If I remove the `exists` check, I don't get this error.  

My babelrc is as follows

```
{
  "presets": ["react", "es2015", "stage-0", "airbnb"],

  "plugins": [
    "transform-runtime",
    "add-module-exports",
    "transform-decorators-legacy",
    "transform-react-display-name",
    "transform-class-properties"
  ],

  "env": {
    "development": {
      "plugins": [
        "typecheck"
      ]
    }
  }
}
```

Any idea what might be going wrong?

**Comment by loudwinston** [comment]
Note that the error `Error: Cannot find module 'babel-plugin-transform-runtime.caseSensitive'` uses whatever id I give in to `global_hook` call

**Comment by halt-hammerzeit** [comment]
```
const actualPath = requireHacker.resolve(requestedPath, module);
```

What is this line of code for?

**Comment by halt-hammerzeit** [comment]
And what value holds `requestedPath`?

**Comment by halt-hammerzeit** [comment]
It's the expected behaviour of the `.resolve()` function when the file isn't found.

**Comment by objectloft** [comment]
So actually my issue was that I wasn't using the original `requestedPath` instead of `actualPath` in the `path.basename` call.  This screwed up require calls to things installed in `node_modules`.

**Comment by loudwinston** [comment]
So actually my issue was that I wasn't using the original `requestedPath` instead of `actualPath` in the `path.basename` call. This screwed up require calls to things installed in `node_modules.`

**Comment by loudwinston** [comment]
I think what threw me off is that the module name in the error that gets thrown had the id of the global hook in it.  I think its because you're creating a `resolved_path` that includes this id here https://github.com/halt-hammerzeit/require-hacker/blob/master/source/require%20hacker.js#L125

I'm sure my particular problem is a bit of an edge case, so I'm not sure it's worth it to change code/docs to make this issue clear to other users.  

Thanks again for your help.

**Comment by halt-hammerzeit** [comment]
You still haven't answered what was the value of `requestedPath`.

> the module name in the error that gets thrown has the id of the global hook in it

That's how it's implemented and you weren't supposed to see that postfixed path.

**Comment by loudwinston** [comment]
The path was `babel-preset-es2015`.  It was the first entry in my `.babelrc`

**Comment by loudwinston** [comment]
There's actually a bit more going on here.  Depending on what I do if the module doesn't exist in my check, I get different behavior.

I will upload a sample project with the problem and a description later in the day.

**Comment by halt-hammerzeit** [comment]
I don't think I'm interested too much in maintaining this repo, but I can answer some questions

**Comment by loudwinston** [comment]
Okay, it's not a big concern of mine as I've solved my immediate issue.  I'll still upload a sample and you can handle it however you think is appropriate.
